services:
  palazon.teste.docker.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TestDb;User Id=sa;Password=Palazon@2024;TrustServerCertificate=True;Encrypt=True;
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  sqlserver:
    environment:
      SA_PASSWORD: "Palazon@2024"
      ACCEPT_EULA: "Y"