services:
  palazon.teste.docker.api:
    image: ${DOCKER_REGISTRY-}palazontestedockerapi
    build:
      context: .
      dockerfile: Palazon.Teste.Docker.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TestDb;User Id=sa;Password=Palazon@2024;TrustServerCertificate=True;Encrypt=True;

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Palazon@2024"
      ACCEPT_EULA: "Y"
    networks:
      - default

networks:
  default:
    driver: bridge